# Generated by Django 4.1.4 on 2023-01-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=40)),
                ('prix_achat', models.FloatField()),
                ('prix_vente_gros', models.FloatField()),
                ('prix_vente_detaill', models.FloatField()),
            ],
        ),
    ]
