# Generated by Django 4.1.4 on 2023-01-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Depense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depense_dynamique',
            name='montant',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='depense_statique',
            name='montant',
            field=models.FloatField(),
        ),
    ]
