# Generated by Django 4.1.4 on 2023-01-18 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produit', '0001_initial'),
        ('Vendeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True)),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendeur.vendeur')),
            ],
        ),
        migrations.CreateModel(
            name='ProduitCharger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Charge.charge')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Produit.produit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='produitcharger',
            constraint=models.UniqueConstraint(fields=('produit', 'charge'), name='once_per_product_sale'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('vendeur', 'date'), name='once_per_vendeur'),
        ),
    ]
