# Generated by Django 4.1.4 on 2023-01-18 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendeur', '0001_initial'),
        ('Charge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='Vendeur.vendeur'),
        ),
        migrations.AlterField(
            model_name='produitcharger',
            name='charge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='Charge.charge'),
        ),
    ]
