# Generated by Django 4.1.4 on 2023-01-18 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vendeur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.FloatField()),
                ('date', models.DateField()),
                ('vendeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Vendeur.vendeur')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gasoil',
            constraint=models.UniqueConstraint(fields=('vendeur', 'date'), name='once_per_vendeur_date'),
        ),
    ]
