# Generated by Django 4.1.4 on 2023-01-18 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vendeur', '0001_initial'),
        ('Gasoil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasoil',
            name='vendeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gasoils', to='Vendeur.vendeur'),
        ),
    ]
